{*********************************
 *   Indy Clients components     *
 *********************************}
procedure RegisterUnit_IdTCPClient;
begin
  RegisterComponents(RSRegIndyClients, [TIdTCPClient]);
end;


procedure RegisterUnit_IdUDPClient;
begin
  RegisterComponents(RSRegIndyClients, [TIdUDPClient]);
end;

procedure RegisterUnit_IdDayTime;
begin
  RegisterComponents(RSRegIndyClients, [TIdDayTime]);
end;

procedure RegisterUnit_IdDayTimeUDP;
begin
  RegisterComponents(RSRegIndyClients, [TIdDayTimeUDP]);
end;

procedure RegisterUnit_IdDNSResolver;
begin
  RegisterComponents(RSRegIndyClients, [TIdDNSResolver]);
end;

procedure RegisterUnit_IdEcho;
begin
  RegisterComponents(RSRegIndyClients, [TIdEcho]);
end;

procedure RegisterUnit_IdEchoUDP;
begin
  RegisterComponents(RSRegIndyClients, [TIdEchoUDP]);
end;

procedure RegisterUnit_IdFinger;
begin
  RegisterComponents(RSRegIndyClients, [TIdFinger]);
end;

procedure RegisterUnit_IdFTP;
begin
  RegisterComponents(RSRegIndyClients, [TIdFTP]);
end;

procedure RegisterUnit_IdGopher;
begin
  RegisterComponents(RSRegIndyClients, [TIdGopher]);
end;

procedure RegisterUnit_IdHTTP;
begin
  RegisterComponents(RSRegIndyClients, [TIdHTTP]);
end;

procedure RegisterUnit_IdIcmpClient;
begin
  RegisterComponents(RSRegIndyClients, [TIdIcmpClient]);
end;

procedure RegisterUnit_IdIdent;
begin
  RegisterComponents(RSRegIndyClients, [TIdIdent]);
end;

procedure RegisterUnit_IdIMAP4;
begin
  RegisterComponents(RSRegIndyClients, [TIdIMAP4]);
end;

procedure RegisterUnit_IdIPMCastClient;
begin
  RegisterComponents(RSRegIndyClients, [TIdIPMCastClient]);
end;

procedure RegisterUnit_IdIRC;
begin
  RegisterComponents(RSRegIndyClients, [TIdIRC]);
end;

procedure RegisterUnit_IdLPR;
begin
  RegisterComponents(RSRegIndyClients, [TIdLPR]);
end;

procedure RegisterUnit_IdNNTP;
begin
  RegisterComponents(RSRegIndyClients, [TIdNNTP]);
end;

procedure RegisterUnit_IdPOP3;
begin
  RegisterComponents(RSRegIndyClients, [TIdPOP3]);
end;

procedure RegisterUnit_IdQotd;
begin
  RegisterComponents(RSRegIndyClients, [TIdQotd]);
end;

procedure RegisterUnit_IdQOTDUDP;
begin
  RegisterComponents(RSRegIndyClients, [TIdQOTDUDP]);
end;

procedure RegisterUnit_IdRexec;
begin
  RegisterComponents(RSRegIndyClients, [TIdRexec]);
end;

procedure RegisterUnit_IdRSH;
begin
  RegisterComponents(RSRegIndyClients, [TIdRSH]);
end;

procedure RegisterUnit_IdSMTP;
begin
  RegisterComponents(RSRegIndyClients, [TIdSMTP]);
end;

procedure RegisterUnit_IdSNMP;
begin
  RegisterComponents(RSRegIndyClients, [TIdSNMP]);
end;

procedure RegisterUnit_IdSNPP;
begin
  RegisterComponents(RSRegIndyClients, [TIdSNPP]);
end;

procedure RegisterUnit_IdSNTP;
begin
  RegisterComponents(RSRegIndyClients, [TIdSNTP]);
end;

procedure RegisterUnit_IdSysLog;
begin
  RegisterComponents(RSRegIndyClients, [TIdSysLog]);
end;

procedure RegisterUnit_IdTelnet;
begin
  RegisterComponents(RSRegIndyClients, [TIdTelnet]);
end;

procedure RegisterUnit_IdTime;
begin
  RegisterComponents(RSRegIndyClients2, [TIdTime]);
end;

procedure RegisterUnit_IdTimeUDP;
begin
  RegisterComponents(RSRegIndyClients2, [TIdTimeUDP]);
end;

procedure RegisterUnit_IdTrivialFTP;
begin
  RegisterComponents(RSRegIndyClients2, [TIdTrivialFTP]);
end;

procedure RegisterUnit_IdWhois;
begin
  RegisterComponents(RSRegIndyClients2, [TIdWhois]);
end;

